apiVersion: v1
kind: Pod
metadata:
  name: stockticker
  namespace: default
  labels:
    app.kubernetes.io/name: st
spec:
   containers:
   - name: stockticker-container
     image: giselle007/stockticker:v2
     ports: 
       - containerPort: 8501
         name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: stockticker-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: st
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
apiVersion: v1
kind: Secret
metadata:
  name: apikey
  namespace: default
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm